language: emacs-lisp

env:
  - EMACS=emacs24

before_install:
  - if [ "$EMACS" = 'emacs24' ]; then
      sudo add-apt-repository -y ppa:cassou/emacs &&
      sudo apt-get update -qq &&
      sudo apt-get install -qq
          emacs24 emacs24-el emacs24-common-non-dfsg emacs-goodies-el;
    fi

# run the tests
script:
  - NO_CHECK_EMACS_PACKAGES=1 /bin/bash ./autogen.sh && cd test && make check-elget
