language: emacs

install:
  # Install emacs.
  - "sudo apt-get install emacs23-nox"

# run the tests
script:
  - curl -fsSkL https://raw.github.com/rejeep/carton/master/go | sh
  - bash ~/.carton/bin/carton
  - elpath=$(emacs -batch -q -no-site-file -eval "(message (apply 'concat (mapcar (lambda(x) (concat x \":\")) load-path)))" 2>&1)
  - test_simple=/home/travis/build/rocky/emacs-dbgr/test-simple-20130710.1126
  - elpath=${elpath}${test_simple}
  - # ls -lR /home/travis
  - echo $elpath
  - EMACSLOADPATH=$elpath /bin/sh ./autogen.sh && EMACSLOADPATH=$elpath make check
