language: emacs-lisp
sudo: no

env:
#  - EVM_EMACS=emacs-26.3-travis # Broken on travis
 - EVM_EMACS=emacs-25.3-travis
 - EVM_EMACS=emacs-25.2-travis

# Install EVM, version EVM_EMACS
install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip

# run the tests
script:
  - ./run-travis-ci.sh
